Update pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -1,23 +1,71 @@
-name: Pylint
+name: Pylint Check
 
-on: [push]
+on:
+  push:
+    branches: [ "main" ]
+  pull_request:
+    branches: [ "main" ]
 
 jobs:
-  build:
+  pylint-check:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        python-version: ["3.8", "3.9", "3.10"]
+
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v3
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-    - name: Analysing the code with pylint
-      run: |
-        pylint $(git ls-files '*.py')
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11.0'
+
+      - name: Install dependencies
+        run: |
+          pip install pylint
+
+      - name: Run Pylint
+        shell: bash
+        run: |
+          # Get the list of changed files and calculate the total pylint score for them
+          
+          # Get the list of changed files
+          { # try
+            changes=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep '\.py$')
+          } || { # catch
+            if [ $? -eq 1 ]; then
+              echo "No python file changes found in the pull request."
+              exit 0
+            fi
+          }
+          
+          echo -e "changes:\n$changes\n"
+          # Make sure to include only the files that exist
+          changed_files=""
+          for file in $changes; do
+            if [ -f "$file" ]; then
+              changed_files="$changed_files $file"
+            fi
+          done
+          echo -e "Changed existing files:\n$changed_files\n"
+          
+          # Check if there are any changed Python files
+          if [ -z "$changed_files" ]; then
+            echo "No Python files changed."
+            exit 0
+          fi
+
+          # Run pylint on the changed files and capture the score
+          { # try
+            pylint_score=$(pylint --rcfile pylintrc $changed_files | grep 'Your code has been rated at' | awk '{print $7}' | cut -d '/' -f 1)
+          } || { # catch
+            echo "Pylint failed to run with exit code: $?"
+          }
+          # Check if the score is below 9
+          if (( $(echo "$pylint_score < 9" | bc -l) )); then
+            echo "Pylint score is below 9: $pylint_score"
+            exit 1
+          else
+            echo "Pylint score is acceptable: $pylint_score"
+          fi
